name: Python Tests

# Déclencheurs : à chaque push ou pull request sur la branche main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Définir les jobs à exécuter
jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Choisissez la version de Python que vous utilisez

    # Étape 3: Installer les dépendances (Black et Ruff)
    - name: Install dependencies
      run: |
        pip install black ruff


    # Étape 5: Exécuter Black (vérification de formatage)
    - name: Run Black (check)
      run: |
        black --check --line-length=120 .

    # Étape 6: Exécuter Ruff (analyse statique)
    - name: Run Ruff
      run: |
        ruff check .
        ruff format .

  test:
    # Le job s'exécute sur une machine virtuelle Ubuntu
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Choisissez la version de Python que vous utilisez
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        PYTHONPATH='.'
        pytest

  build-front:
    runs-on: ubuntu-latest
    needs: test

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Docker Buildx (for multi-platform builds, optional)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      env:
        GHCR_USERNAME: <GITHUB_USERNAME>
        GHCR_TOKEN: ${{ secrets.TOKEN }}
      run: |
        docker login ghcr.io -u $GHCR_USERNAME -p $GHCR_TOKEN

    # Build the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./app/frontend
        push: true
        tags: ghcr.io/arnolec/front-transport:latest
  

  build-back:
    runs-on: ubuntu-latest
    needs: test

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Docker Buildx (for multi-platform builds, optional)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      env:
        GHCR_USERNAME: <GITHUB_USERNAME>
        GHCR_TOKEN: ${{ secrets.TOKEN }}
      run: |
        docker login ghcr.io -u $GHCR_USERNAME -p $GHCR_TOKEN

    # Build the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/arnolec/back-transport:latest